version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
  test-python-version:
    parameters:
      version:
        type: string
        default: "latest"
    docker:
      - image: circleci/python:<< parameters.version >>
    steps:
      - checkout
      - run:
          name: Run test for Python << parameters.version >>
          command: |
            # Install surround
            sudo python setup.py install

            # Run tests
            sudo python setup.py test

            # Run pylint tests
            pylint setup.py
            find surround/ -iname "*.py" | xargs pylint
            find examples/ -iname "*.py" | xargs pylint

            # Run examples
            ls examples/ | xargs -n 1 -I '{}' python examples/'{}'/main.py

  release:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - run:
          name: Release to Pypi
          command: |
            # Install required packages
            python -m pip install --user --upgrade setuptools wheel twine

            # Setup Pypi config
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "repository:https://upload.pypi.org/legacy/" >> ~/.pypirc
            echo -e "username:$PYPI_USERNAME" >> ~/.pypirc
            echo -e "password:$PYPI_PASSWORD" >> ~/.pypirc

            # Build package
            VERSION_TAG=$(git tag -l --points-at HEAD) python setup.py sdist bdist_wheel

            # Upload package for distribution
            python -m twine upload --repository pypi dist/*

workflows:
  version: 2.1
  test-and-relese:
    jobs:
    - build
    - test-python-version:
        version: "3.6.5"
    - test-python-version
    - release:
        filters:
          tags:
            only: /v([0-9]+)\.([0-9]+)\.([0-9]+)?$/
          branches:
            ignore: /.*/
